spring:
  config:
    import: secret-local.yml

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        format-sql: false
        highlight_sql: true
    defer-datasource-initialization: true
    open-in-view: false

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  h2:
    console:
      enabled: true
      path: /h2-console

  ai:
    model:
      chat: google-genai

    google:
      genai:
        api-key: ${secret.ai.google.api-key}
        project-id: ${secret.ai.google.project-id}
        location: asia-northeast3
        chat:
          options:
            model: gemini-2.5-flash-lite

    openai:
      api-key: ${secret.ai.openai.api-key}

discord:
  bot:
    token: ${secret.discord.token}

logging:
  level:
    org.hibernate.SQL: DEBUG            # 실행되는 SQL 로그 출력
    org.hibernate.orm.jdbc.bind: TRACE
